server:
  servlet:
    context-path: /f1rst/api

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger

spring:
  data:
    mongodb:
      uri: mongodb+srv://sa:153321@cluster0.htbyici.mongodb.net/f1rst?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true